// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("WaveEngine.HoloLens linux")]
[assembly: AssemblyCompanyAttribute("Wave Engine")]
[assembly: AssemblyDescriptionAttribute("linux")]
[assembly: AssemblyCopyrightAttribute("Copyright (c) Wave Engine 2017")]
[assembly: GuidAttribute("EF5A79B7-E191-499B-8AA0-514FE9C5AFFD")]
[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyVersionAttribute("2.3.1.0000")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "2.3.1.0000";
    }
}
