// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("WaveEngine.Social iOS")]
[assembly: AssemblyCompanyAttribute("Wave Engine")]
[assembly: AssemblyDescriptionAttribute("iOS")]
[assembly: AssemblyCopyrightAttribute("Copyright (c) Wave Engine 2015")]
[assembly: GuidAttribute("8f4157b5-6d0c-493a-b824-405c6b86e9b0")]
[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyVersionAttribute("2.0.5.*")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "2.0.5.*";
    }
}
