// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("WaveEngine.OpenVR Windows")]
[assembly: AssemblyCompanyAttribute("Wave Engine")]
[assembly: AssemblyDescriptionAttribute("Windows")]
[assembly: AssemblyCopyrightAttribute("Copyright (c) Wave Engine 2016")]
[assembly: GuidAttribute("ebc4a8e9-f457-43a2-a6d8-fcb506fe13cb")]
[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyVersionAttribute("2.5.0.0000")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "WaveEngine.OpenVR Windows";
        internal const System.String AssemblyCompany = "Wave Engine";
        internal const System.String AssemblyDescription = "Windows";
        internal const System.String AssemblyCopyright = "Copyright (c) Wave Engine 2016";
        internal const System.String Guid = "ebc4a8e9-f457-43a2-a6d8-fcb506fe13cb";
        internal const System.Boolean ComVisible = false;
        internal const System.String AssemblyVersion = "2.5.0.0000";
    }
}
