//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 10/7/2015 5:20:17 PM
namespace OculusTest
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/small.mp4 </summary>
            public const string small_mp4 = "Content/Assets/small.mp4";
            
            /// <summary> Path to Content/Assets/TvRoomLightingMap.png </summary>
            public const string TvRoomLightingMap_png = "Content/Assets/TvRoomLightingMap.png";
            
            public sealed class Model
            {
                
                /// <summary> Path to Content/Assets/Model/isis.fbx </summary>
                public const string isis_fbx = "Content/Assets/Model/isis.fbx";
                
                /// <summary> Path to Content/Assets/Model/TvRoom.fbx </summary>
                public const string TvRoom_fbx = "Content/Assets/Model/TvRoom.fbx";
            }
            
            public sealed class Sounds
            {
                
                /// <summary> Path to Content/Assets/Sounds/engines_1.wav </summary>
                public const string engines_1_wav = "Content/Assets/Sounds/engines_1.wav";
                
                /// <summary> Path to Content/Assets/Sounds/torchFireSound.wav </summary>
                public const string torchFireSound_wav = "Content/Assets/Sounds/torchFireSound.wav";
            }
            
            public sealed class Texture
            {
                
                /// <summary> Path to Content/Assets/Texture/Chair_Difuse.png </summary>
                public const string Chair_Difuse_png = "Content/Assets/Texture/Chair_Difuse.png";
                
                /// <summary> Path to Content/Assets/Texture/isis_diffuse.png </summary>
                public const string isis_diffuse_png = "Content/Assets/Texture/isis_diffuse.png";
                
                /// <summary> Path to Content/Assets/Texture/isis_normal.png </summary>
                public const string isis_normal_png = "Content/Assets/Texture/isis_normal.png";
                
                /// <summary> Path to Content/Assets/Texture/isis_spec.png </summary>
                public const string isis_spec_png = "Content/Assets/Texture/isis_spec.png";
                
                /// <summary> Path to Content/Assets/Texture/parketFloor_Difuse.png </summary>
                public const string parketFloor_Difuse_png = "Content/Assets/Texture/parketFloor_Difuse.png";
                
                /// <summary> Path to Content/Assets/Texture/table_Difuse.png </summary>
                public const string table_Difuse_png = "Content/Assets/Texture/table_Difuse.png";
                
                /// <summary> Path to Content/Assets/Texture/tile1.png </summary>
                public const string tile1_png = "Content/Assets/Texture/tile1.png";
                
                /// <summary> Path to Content/Assets/Texture/Tv_Difuse.png </summary>
                public const string Tv_Difuse_png = "Content/Assets/Texture/Tv_Difuse.png";
            }
            
            public sealed class Material
            {
                
                /// <summary> Path to Content/Assets/Material/ChairMaterial.wmat </summary>
                public const string ChairMaterial = "Content/Assets/Material/ChairMaterial.wmat";
                
                /// <summary> Path to Content/Assets/Material/EyeL.wmat </summary>
                public const string EyeL = "Content/Assets/Material/EyeL.wmat";
                
                /// <summary> Path to Content/Assets/Material/EyeR.wmat </summary>
                public const string EyeR = "Content/Assets/Material/EyeR.wmat";
                
                /// <summary> Path to Content/Assets/Material/MyMaterial(1).wmat </summary>
                public const string MyMaterial_1_ = "Content/Assets/Material/MyMaterial(1).wmat";
                
                /// <summary> Path to Content/Assets/Material/MyMaterial.wmat </summary>
                public const string MyMaterial = "Content/Assets/Material/MyMaterial.wmat";
                
                /// <summary> Path to Content/Assets/Material/ParketMaterial.wmat </summary>
                public const string ParketMaterial = "Content/Assets/Material/ParketMaterial.wmat";
                
                /// <summary> Path to Content/Assets/Material/TableMaterial.wmat </summary>
                public const string TableMaterial = "Content/Assets/Material/TableMaterial.wmat";
                
                /// <summary> Path to Content/Assets/Material/TVMaterial.wmat </summary>
                public const string TVMaterial = "Content/Assets/Material/TVMaterial.wmat";
                
                /// <summary> Path to Content/Assets/Material/TVScreenMaterial.wmat </summary>
                public const string TVScreenMaterial = "Content/Assets/Material/TVScreenMaterial.wmat";
            }
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
