// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("WaveEngine.LeapMotion Windows")]
[assembly: AssemblyCompanyAttribute("Wave Engine")]
[assembly: AssemblyDescriptionAttribute("Windows")]
[assembly: AssemblyCopyrightAttribute("Copyright (c) Wave Engine 2015")]
[assembly: GuidAttribute("a11c4c30-86e7-49c1-a8d5-a455a8623559")]
[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyVersionAttribute("2.0.5.*")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "2.0.5.*";
    }
}
