// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("WaveEngine.LeapMotion Windows")]
[assembly: AssemblyCompanyAttribute("Wave Engine")]
[assembly: AssemblyDescriptionAttribute("Windows")]
[assembly: AssemblyCopyrightAttribute("Copyright (c) Wave Engine 2016")]
[assembly: GuidAttribute("a11c4c30-86e7-49c1-a8d5-a455a8623559")]
[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyVersionAttribute("2.3.0.0000")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "2.3.0.0000";
    }
}
