// Copyright © 2018 Wave Engine S.L. All rights reserved. Use is subject to license terms.

using WaveEngine.Common.Math;

namespace WaveEngine.ARMobile
{
    /// <summary>
    /// A result generated by the <see cref="ARMobileService.HitTest"/> method
    /// </summary>
    public class ARMobileHitTestResult
    {
        /// <summary>
        /// The kind of object detected
        /// </summary>
        public ARMobileHitType HitType;

        /// <summary>
        /// The position and orientation of the detected object relative to the world coordinate system
        /// </summary>
        public Matrix WorldTransform;

        /// <summary>
        /// The distance, in meters, to the detected object
        /// </summary>
        public float Distance;

        /// <summary>
        /// If not null, the <see cref="ARMobileAnchor"/> of the detected surface.
        /// </summary>
        public ARMobileAnchor Anchor;
    }
}
