// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("WaveEngine.TiledMap linux")]
[assembly: AssemblyCompanyAttribute("Wave Engine")]
[assembly: AssemblyDescriptionAttribute("linux")]
[assembly: AssemblyCopyrightAttribute("Copyright (c) Wave Engine 2016")]
[assembly: GuidAttribute("a142bf2e-e6db-41ec-b84d-88fe9b566493")]
[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyVersionAttribute("2.0.6.*")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "2.0.6.*";
    }
}
