// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("WaveEngine.LeapMotion Windows")]
[assembly: AssemblyCompanyAttribute("Wave Engine")]
[assembly: AssemblyCopyrightAttribute("Copyright Wave Engine 2015")]
[assembly: GuidAttribute("a11c4c30-86e7-49c1-a8d5-a455a8623559")]
[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyVersionAttribute("1.9.9.70")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.9.9.70";
    }
}
