// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("WaveEngine.Kinect Windows")]
[assembly: AssemblyCompanyAttribute("Wave Engine")]
[assembly: AssemblyDescriptionAttribute("Windows")]
[assembly: AssemblyCopyrightAttribute("Copyright (c) Wave Engine 2016")]
[assembly: GuidAttribute("0c415f19-2e5d-4047-9ccc-149d269fd73f")]
[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyVersionAttribute("2.5.0.0000")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "WaveEngine.Kinect Windows";
        internal const System.String AssemblyCompany = "Wave Engine";
        internal const System.String AssemblyDescription = "Windows";
        internal const System.String AssemblyCopyright = "Copyright (c) Wave Engine 2016";
        internal const System.String Guid = "0c415f19-2e5d-4047-9ccc-149d269fd73f";
        internal const System.Boolean ComVisible = false;
        internal const System.String AssemblyVersion = "2.5.0.0000";
    }
}
