// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("WaveEngine.Vuforia iOS")]
[assembly: AssemblyCompanyAttribute("Wave Engine")]
[assembly: AssemblyDescriptionAttribute("iOS")]
[assembly: AssemblyCopyrightAttribute("Copyright (c) Wave Engine 2015")]
[assembly: GuidAttribute("E210DB9F-8AA2-4CD7-BDB8-CF78A871B236")]
[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyVersionAttribute("1.9.11.24")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.9.11.24";
    }
}
