// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("WaveEngine.Cardboard Windows")]
[assembly: AssemblyCompanyAttribute("Wave Engine")]
[assembly: AssemblyDescriptionAttribute("Windows")]
[assembly: AssemblyCopyrightAttribute("Copyright (c) Wave Engine 2016")]
[assembly: GuidAttribute("82619f73-a53c-443a-b88f-ae906c4622e7")]
[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyVersionAttribute("2.0.6.*")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "2.0.6.*";
    }
}
