// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("WaveEngine.Vuforia Android")]
[assembly: AssemblyCompanyAttribute("Wave Engine")]
[assembly: AssemblyDescriptionAttribute("Android")]
[assembly: AssemblyCopyrightAttribute("Copyright (c) Wave Engine 2016")]
[assembly: GuidAttribute("E210DB9F-8AA2-4CD7-BDB8-CF78A871B236")]
[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyVersionAttribute("2.5.0.0000")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "WaveEngine.Vuforia Android";
        internal const System.String AssemblyCompany = "Wave Engine";
        internal const System.String AssemblyDescription = "Android";
        internal const System.String AssemblyCopyright = "Copyright (c) Wave Engine 2016";
        internal const System.String Guid = "E210DB9F-8AA2-4CD7-BDB8-CF78A871B236";
        internal const System.Boolean ComVisible = false;
        internal const System.String AssemblyVersion = "2.5.0.0000";
    }
}
