// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("WaveEngine.Analytics linux")]
[assembly: AssemblyCompanyAttribute("Wave Engine")]
[assembly: AssemblyDescriptionAttribute("linux")]
[assembly: AssemblyCopyrightAttribute("Copyright (c) Wave Engine 2015")]
[assembly: GuidAttribute("63b34c51-621b-44a2-a9a2-f15da07281a9")]
[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyVersionAttribute("1.9.11.24")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.9.11.24";
    }
}
