//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


using System;
using System.Runtime.InteropServices;

namespace Noesis
{

public class ContextMenuEventArgs : RoutedEventArgs {
  private HandleRef swigCPtr;

  internal ContextMenuEventArgs(IntPtr cPtr, bool cMemoryOwn) : base(cPtr, cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(ContextMenuEventArgs obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~ContextMenuEventArgs() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          NoesisGUI_PINVOKE.delete_ContextMenuEventArgs(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public float CursorLeft {
    get {
      return GetCursorLeftHelper();
    }
  }

  public float CursorTop {
    get {
      return GetCursorTopHelper();
    }
  }

  public ContextMenuEventArgs(object s, RoutedEvent e, float left, float top) : this(NoesisGUI_PINVOKE.new_ContextMenuEventArgs__SWIG_0(Noesis.Extend.GetInstanceHandle(s), RoutedEvent.getCPtr(e), left, top), true) {
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
  }

  public ContextMenuEventArgs(object s, RoutedEvent e, float left) : this(NoesisGUI_PINVOKE.new_ContextMenuEventArgs__SWIG_1(Noesis.Extend.GetInstanceHandle(s), RoutedEvent.getCPtr(e), left), true) {
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
  }

  public ContextMenuEventArgs(object s, RoutedEvent e) : this(NoesisGUI_PINVOKE.new_ContextMenuEventArgs__SWIG_2(Noesis.Extend.GetInstanceHandle(s), RoutedEvent.getCPtr(e)), true) {
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
  }

  private float GetCursorLeftHelper() {
    float ret = NoesisGUI_PINVOKE.ContextMenuEventArgs_GetCursorLeftHelper(swigCPtr);
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private float GetCursorTopHelper() {
    float ret = NoesisGUI_PINVOKE.ContextMenuEventArgs_GetCursorTopHelper(swigCPtr);
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}

