//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


using System;
using System.Runtime.InteropServices;

namespace Noesis
{

public enum FrameworkPropertyMetadataOptions {
  None = 1 << 0,
  AffectsMeasure = 1 << 1,
  AffectsArrange = 1 << 2,
  AffectsParentMeasure = 1 << 3,
  AffectsParentArrange = 1 << 4,
  AffectsRender = 1 << 5,
  Inherits = 1 << 6,
  OverridesInheritanceBehavior = 1 << 7,
  NotDataBindable = 1 << 8,
  BindsTwoWayByDefault = 1 << 9,
  SubPropertiesDoNotAffectRender = 1 << 11,
  UpdateSourceTriggerLostFocus = 1 << 12,
  UpdateSourceTriggerExplicit = 1 << 13
}

}

