//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


using System;
using System.Runtime.InteropServices;

namespace Noesis
{

public partial class FrameworkPropertyMetadata : UIPropertyMetadata {
  internal new static FrameworkPropertyMetadata CreateProxy(IntPtr cPtr, bool cMemoryOwn) {
    return new FrameworkPropertyMetadata(cPtr, cMemoryOwn);
  }

  internal FrameworkPropertyMetadata(IntPtr cPtr, bool cMemoryOwn) : base(cPtr, cMemoryOwn) {
  }

  internal static HandleRef getCPtr(FrameworkPropertyMetadata obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  protected FrameworkPropertyMetadata() {
  }

  public bool AffectsMeasure {
    get {
      bool ret = NoesisGUI_PINVOKE.FrameworkPropertyMetadata_AffectsMeasure_get(swigCPtr);
      if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool AffectsArrange {
    get {
      bool ret = NoesisGUI_PINVOKE.FrameworkPropertyMetadata_AffectsArrange_get(swigCPtr);
      if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool AffectsParentMeasure {
    get {
      bool ret = NoesisGUI_PINVOKE.FrameworkPropertyMetadata_AffectsParentMeasure_get(swigCPtr);
      if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool AffectsParentArrange {
    get {
      bool ret = NoesisGUI_PINVOKE.FrameworkPropertyMetadata_AffectsParentArrange_get(swigCPtr);
      if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool AffectsRender {
    get {
      bool ret = NoesisGUI_PINVOKE.FrameworkPropertyMetadata_AffectsRender_get(swigCPtr);
      if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool Inherits {
    get {
      bool ret = NoesisGUI_PINVOKE.FrameworkPropertyMetadata_Inherits_get(swigCPtr);
      if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool OverridesInheritanceBehavior {
    get {
      bool ret = NoesisGUI_PINVOKE.FrameworkPropertyMetadata_OverridesInheritanceBehavior_get(swigCPtr);
      if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool IsNotDataBindable {
    get {
      bool ret = NoesisGUI_PINVOKE.FrameworkPropertyMetadata_IsNotDataBindable_get(swigCPtr);
      if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool BindsTwoWayByDefault {
    get {
      bool ret = NoesisGUI_PINVOKE.FrameworkPropertyMetadata_BindsTwoWayByDefault_get(swigCPtr);
      if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public UpdateSourceTrigger DefaultUpdateSourceTrigger {
    get {
      UpdateSourceTrigger ret = (UpdateSourceTrigger)NoesisGUI_PINVOKE.FrameworkPropertyMetadata_DefaultUpdateSourceTrigger_get(swigCPtr);
      if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool SubPropertiesDoNotAffectRender {
    get {
      bool ret = NoesisGUI_PINVOKE.FrameworkPropertyMetadata_SubPropertiesDoNotAffectRender_get(swigCPtr);
      if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  new internal static IntPtr GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.FrameworkPropertyMetadata_GetStaticType();
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}

