//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


using System;
using System.Runtime.InteropServices;

namespace Noesis
{

public class ManipulationDeltaEventArgs : RoutedEventArgs {
  private HandleRef swigCPtr;

  internal ManipulationDeltaEventArgs(IntPtr cPtr, bool cMemoryOwn) : base(cPtr, cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(ManipulationDeltaEventArgs obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~ManipulationDeltaEventArgs() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          NoesisGUI_PINVOKE.delete_ManipulationDeltaEventArgs(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public Noesis.UIElement ManipulationContainer {
    get {
      return GetManipulationContainerHelper();
    }
  }

  public Noesis.Point ManipulationOrigin {
    get {
      return GetManipulationOriginHelper();
    }
  }

  public Noesis.ManipulationDelta CumulativeManipulation {
    get {
      return GetCumulativeManipulationHelper();
    }
  }

  public Noesis.ManipulationDelta DeltaManipulation {
    get {
      return GetDeltaManipulationHelper();
    }
  }

  public Noesis.ManipulationVelocities Velocities {
    get {
      return GetVelocitiesHelper();
    }
  }

  public bool IsInertial {
    get {
      return GetIsInertialHelper();
    }
  }

  public ManipulationDeltaEventArgs(object s, RoutedEvent e, Visual manipulationContainer, Point manipulationOrigin, ManipulationDelta deltaManipulation, ManipulationDelta cumulativeManipulation, ManipulationVelocities velocities, bool isInertial) : this(NoesisGUI_PINVOKE.new_ManipulationDeltaEventArgs(Noesis.Extend.GetInstanceHandle(s), RoutedEvent.getCPtr(e), Visual.getCPtr(manipulationContainer), ref manipulationOrigin, ManipulationDelta.getCPtr(deltaManipulation), ManipulationDelta.getCPtr(cumulativeManipulation), ManipulationVelocities.getCPtr(velocities), isInertial), true) {
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
  }

  public bool Cancel() {
    bool ret = NoesisGUI_PINVOKE.ManipulationDeltaEventArgs_Cancel(swigCPtr);
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Complete() {
    NoesisGUI_PINVOKE.ManipulationDeltaEventArgs_Complete(swigCPtr);
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
  }

  private UIElement GetManipulationContainerHelper() {
    IntPtr cPtr = NoesisGUI_PINVOKE.ManipulationDeltaEventArgs_GetManipulationContainerHelper(swigCPtr);
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    return (UIElement)Noesis.Extend.GetProxy(cPtr, false);
  }

  private Point GetManipulationOriginHelper() {
    IntPtr ret = NoesisGUI_PINVOKE.ManipulationDeltaEventArgs_GetManipulationOriginHelper(swigCPtr);
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    if (ret != IntPtr.Zero) {
      return Marshal.PtrToStructure<Point>(ret);
    }
    else {
      return new Point();
    }
  }

  private ManipulationDelta GetCumulativeManipulationHelper() {
    ManipulationDelta ret = new ManipulationDelta(NoesisGUI_PINVOKE.ManipulationDeltaEventArgs_GetCumulativeManipulationHelper(swigCPtr), false);
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private ManipulationDelta GetDeltaManipulationHelper() {
    ManipulationDelta ret = new ManipulationDelta(NoesisGUI_PINVOKE.ManipulationDeltaEventArgs_GetDeltaManipulationHelper(swigCPtr), false);
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private ManipulationVelocities GetVelocitiesHelper() {
    ManipulationVelocities ret = new ManipulationVelocities(NoesisGUI_PINVOKE.ManipulationDeltaEventArgs_GetVelocitiesHelper(swigCPtr), false);
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private bool GetIsInertialHelper() {
    bool ret = NoesisGUI_PINVOKE.ManipulationDeltaEventArgs_GetIsInertialHelper(swigCPtr);
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}

