//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


using System;
using System.Runtime.InteropServices;

namespace Noesis
{

public class ScrollEventArgs : RoutedEventArgs {
  private HandleRef swigCPtr;

  internal ScrollEventArgs(IntPtr cPtr, bool cMemoryOwn) : base(cPtr, cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(ScrollEventArgs obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~ScrollEventArgs() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          NoesisGUI_PINVOKE.delete_ScrollEventArgs(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public float NewValue {
    get {
      return GetNewValueHelper();
    }
  }

  public Noesis.ScrollEventType ScrollEventType {
    get {
      return GetScrollEventTypeHelper();
    }
  }

  public ScrollEventArgs(object s, float value, ScrollEventType type) : this(NoesisGUI_PINVOKE.new_ScrollEventArgs(Noesis.Extend.GetInstanceHandle(s), value, (int)type), true) {
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
  }

  private float GetNewValueHelper() {
    float ret = NoesisGUI_PINVOKE.ScrollEventArgs_GetNewValueHelper(swigCPtr);
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private ScrollEventType GetScrollEventTypeHelper() {
    ScrollEventType ret = (ScrollEventType)NoesisGUI_PINVOKE.ScrollEventArgs_GetScrollEventTypeHelper(swigCPtr);
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}

