// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("WaveEngine.OculusRift Windows")]
[assembly: AssemblyCompanyAttribute("Wave Engine")]
[assembly: AssemblyDescriptionAttribute("Windows")]
[assembly: AssemblyCopyrightAttribute("Copyright (c) Wave Engine 2017")]
[assembly: GuidAttribute("3b2cbffb-d52a-4ba0-899f-aa6ce3c3264d")]
[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyVersionAttribute("2.3.1.0000")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "2.3.1.0000";
    }
}
