// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("WaveEngine.Dolby Android")]
[assembly: AssemblyCompanyAttribute("Wave Engine")]
[assembly: AssemblyDescriptionAttribute("Android")]
[assembly: AssemblyCopyrightAttribute("Copyright (c) Wave Engine 2016")]
[assembly: GuidAttribute("f1dd0c12-f863-42b7-910a-78f5351363e2")]
[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyVersionAttribute("2.5.0.0000")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "WaveEngine.Dolby Android";
        internal const System.String AssemblyCompany = "Wave Engine";
        internal const System.String AssemblyDescription = "Android";
        internal const System.String AssemblyCopyright = "Copyright (c) Wave Engine 2016";
        internal const System.String Guid = "f1dd0c12-f863-42b7-910a-78f5351363e2";
        internal const System.Boolean ComVisible = false;
        internal const System.String AssemblyVersion = "2.5.0.0000";
    }
}
